# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
my_dBCPEo <- function(x, mu, sigma, nu, tau, log_ = FALSE, n_cpu = 1L) {
    .Call('_workHORSEmisc_my_dBCPEo', PACKAGE = 'workHORSEmisc', x, mu, sigma, nu, tau, log_, n_cpu)
}

#' @export
my_pBCPEo <- function(q, mu, sigma, nu, tau, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_workHORSEmisc_my_pBCPEo', PACKAGE = 'workHORSEmisc', q, mu, sigma, nu, tau, lower_tail, log_p, n_cpu)
}

#' @export
my_qBCPEo <- function(p, mu, sigma, nu, tau, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_workHORSEmisc_my_qBCPEo', PACKAGE = 'workHORSEmisc', p, mu, sigma, nu, tau, lower_tail, log_p, n_cpu)
}

#' @export
my_dBCT <- function(x, mu, sigma, nu, tau, log_ = FALSE, n_cpu = 1L) {
    .Call('_workHORSEmisc_my_dBCT', PACKAGE = 'workHORSEmisc', x, mu, sigma, nu, tau, log_, n_cpu)
}

#' @export
my_pBCT <- function(q, mu, sigma, nu, tau, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_workHORSEmisc_my_pBCT', PACKAGE = 'workHORSEmisc', q, mu, sigma, nu, tau, lower_tail, log_p, n_cpu)
}

#' @export
my_qBCT <- function(p, mu, sigma, nu, tau, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_workHORSEmisc_my_qBCT', PACKAGE = 'workHORSEmisc', p, mu, sigma, nu, tau, lower_tail, log_p, n_cpu)
}

#' @export
my_dBNB <- function(x, mu, sigma, nu, log = FALSE, n_cpu = 1L) {
    .Call('_workHORSEmisc_my_dBNB', PACKAGE = 'workHORSEmisc', x, mu, sigma, nu, log, n_cpu)
}

#' @export
my_pBNB <- function(q, mu, sigma, nu, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_workHORSEmisc_my_pBNB', PACKAGE = 'workHORSEmisc', q, mu, sigma, nu, lower_tail, log_p, n_cpu)
}

#' @export
my_qBNB <- function(p, mu, sigma, nu, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_workHORSEmisc_my_qBNB', PACKAGE = 'workHORSEmisc', p, mu, sigma, nu, lower_tail, log_p, n_cpu)
}

#' @export
my_qZIBNB <- function(p, mu, sigma, nu, tau, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_workHORSEmisc_my_qZIBNB', PACKAGE = 'workHORSEmisc', p, mu, sigma, nu, tau, lower_tail, log_p, n_cpu)
}

#' @export
my_qZABNB <- function(p, mu, sigma, nu, tau, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_workHORSEmisc_my_qZABNB', PACKAGE = 'workHORSEmisc', p, mu, sigma, nu, tau, lower_tail, log_p, n_cpu)
}

#' @export
my_dDEL <- function(x, mu, sigma, nu, log_ = FALSE, n_cpu = 1L) {
    .Call('_workHORSEmisc_my_dDEL', PACKAGE = 'workHORSEmisc', x, mu, sigma, nu, log_, n_cpu)
}

#' @export
my_pDEL <- function(q, mu, sigma, nu, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_workHORSEmisc_my_pDEL', PACKAGE = 'workHORSEmisc', q, mu, sigma, nu, lower_tail, log_p, n_cpu)
}

#' @export
my_qDEL <- function(p, mu, sigma, nu, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_workHORSEmisc_my_qDEL', PACKAGE = 'workHORSEmisc', p, mu, sigma, nu, lower_tail, log_p, n_cpu)
}

#' @export
my_get_C <- function(x, mu, sigma) {
    .Call('_workHORSEmisc_my_get_C', PACKAGE = 'workHORSEmisc', x, mu, sigma)
}

#' @export
my_dDPO <- function(x, mu, sigma, log_ = FALSE, n_cpu = 1L) {
    .Call('_workHORSEmisc_my_dDPO', PACKAGE = 'workHORSEmisc', x, mu, sigma, log_, n_cpu)
}

#' @export
my_pDPO <- function(q, mu, sigma, lower_tail = TRUE, log_p = FALSE) {
    .Call('_workHORSEmisc_my_pDPO', PACKAGE = 'workHORSEmisc', q, mu, sigma, lower_tail, log_p)
}

#' @export
my_qDPO <- function(p, mu, sigma, lower_tail = TRUE, log_p = FALSE, max_value = 0L, n_cpu = 1L) {
    .Call('_workHORSEmisc_my_qDPO', PACKAGE = 'workHORSEmisc', p, mu, sigma, lower_tail, log_p, max_value, n_cpu)
}

#' @export
run_impactncd_simulation <- function(simulationStructureList, frame, input_list) {
    .Call('_workHORSEmisc_run_impactncd_simulation', PACKAGE = 'workHORSEmisc', simulationStructureList, frame, input_list)
}

#' @export
my_qMN4 <- function(p, mu, sigma, nu, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_workHORSEmisc_my_qMN4', PACKAGE = 'workHORSEmisc', p, mu, sigma, nu, lower_tail, log_p, n_cpu)
}

#' @export
my_dSICHEL <- function(x, mu, sigma, nu, log_ = FALSE, n_cpu = 1L) {
    .Call('_workHORSEmisc_my_dSICHEL', PACKAGE = 'workHORSEmisc', x, mu, sigma, nu, log_, n_cpu)
}

#' @export
my_pSICHEL <- function(q, mu, sigma, nu, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_workHORSEmisc_my_pSICHEL', PACKAGE = 'workHORSEmisc', q, mu, sigma, nu, lower_tail, log_p, n_cpu)
}

#' @export
my_qSICHEL <- function(p, mu, sigma, nu, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_workHORSEmisc_my_qSICHEL', PACKAGE = 'workHORSEmisc', p, mu, sigma, nu, lower_tail, log_p, n_cpu)
}

#' @export
my_qZISICHEL <- function(p, mu, sigma, nu, tau, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_workHORSEmisc_my_qZISICHEL', PACKAGE = 'workHORSEmisc', p, mu, sigma, nu, tau, lower_tail, log_p, n_cpu)
}

#' @export
my_pZISICHEL <- function(q, mu, sigma, nu, tau, lower_tail = TRUE, log_p = FALSE, n_cpu = 1L) {
    .Call('_workHORSEmisc_my_pZISICHEL', PACKAGE = 'workHORSEmisc', q, mu, sigma, nu, tau, lower_tail, log_p, n_cpu)
}

#' @export
carry_forward <- function(x, pid, y) {
    .Call('_workHORSEmisc_carry_forward', PACKAGE = 'workHORSEmisc', x, pid, y)
}

#' @export
carry_backward <- function(x, pid) {
    .Call('_workHORSEmisc_carry_backward', PACKAGE = 'workHORSEmisc', x, pid)
}

#' @export
mk_new_simulant_markers <- function(pid) {
    .Call('_workHORSEmisc_mk_new_simulant_markers', PACKAGE = 'workHORSEmisc', pid)
}

#' @export
identify_longdead <- function(x, pid) {
    .Call('_workHORSEmisc_identify_longdead', PACKAGE = 'workHORSEmisc', x, pid)
}

#' @export
identify_invitees <- function(elig, prev_inv, prb, freq, pid) {
    .Call('_workHORSEmisc_identify_invitees', PACKAGE = 'workHORSEmisc', elig, prev_inv, prb, freq, pid)
}

#' @export
hc_effect <- function(x, prb_of_continuation, pid) {
    .Call('_workHORSEmisc_hc_effect', PACKAGE = 'workHORSEmisc', x, prb_of_continuation, pid)
}

#' @export
fbound <- function(x, a, b) {
    .Call('_workHORSEmisc_fbound', PACKAGE = 'workHORSEmisc', x, a, b)
}

dtsubset <- function(x, rows, cols) {
    .Call('_workHORSEmisc_dtsubset', PACKAGE = 'workHORSEmisc', x, rows, cols)
}

#' @export
QDiabetes <- function(df, surv = 1L) {
    .Call('_workHORSEmisc_QDiabetes', PACKAGE = 'workHORSEmisc', df, surv)
}

#' @export
QDiabetes_vec_inputs <- function(age, sex, b_corticosteroids, b_treatedhyp, bmi, ethrisk, fh_diab, smoke_cat, town, surv = 1L) {
    .Call('_workHORSEmisc_QDiabetes_vec_inputs', PACKAGE = 'workHORSEmisc', age, sex, b_corticosteroids, b_treatedhyp, bmi, ethrisk, fh_diab, smoke_cat, town, surv)
}

#' @export
Qrisk2 <- function(df, ignore_bmi = FALSE, ignore_sbp = FALSE, ignore_chol = FALSE) {
    .Call('_workHORSEmisc_Qrisk2', PACKAGE = 'workHORSEmisc', df, ignore_bmi, ignore_sbp, ignore_chol)
}

#' @export
fscramble_trajectories <- function(x, pid, jumpiness = 1.0, inplace = TRUE) {
    .Call('_workHORSEmisc_fscramble_trajectories', PACKAGE = 'workHORSEmisc', x, pid, jumpiness, inplace)
}

#' @export
shift_bypidNum <- function(x, lag, replace, id) {
    .Call('_workHORSEmisc_shift_bypidNum', PACKAGE = 'workHORSEmisc', x, lag, replace, id)
}

#' @export
shift_bypidInt <- function(x, lag, replace, id) {
    .Call('_workHORSEmisc_shift_bypidInt', PACKAGE = 'workHORSEmisc', x, lag, replace, id)
}

#' @export
shift_bypidBool <- function(x, lag, replace, id) {
    .Call('_workHORSEmisc_shift_bypidBool', PACKAGE = 'workHORSEmisc', x, lag, replace, id)
}

#' @export
shift_bypidStr <- function(x, lag, replace, id) {
    .Call('_workHORSEmisc_shift_bypidStr', PACKAGE = 'workHORSEmisc', x, lag, replace, id)
}

#' @export
simsmok <- function(df, pr_relapse_below_30, pr_relapse_30_50, pr_relapse_above_50, relapse_cutoff, relapse_effect, age_min = 0L, age_max = 100L) {
    invisible(.Call('_workHORSEmisc_simsmok', PACKAGE = 'workHORSEmisc', df, pr_relapse_below_30, pr_relapse_30_50, pr_relapse_above_50, relapse_cutoff, relapse_effect, age_min, age_max))
}

#' @export
simsmok_sc <- function(df, pr_relapse_below_30, pr_relapse_30_50, pr_relapse_above_50, relapse_cutoff, row_sel, relapse_effect, age_min = 0L, age_max = 100L) {
    invisible(.Call('_workHORSEmisc_simsmok_sc', PACKAGE = 'workHORSEmisc', df, pr_relapse_below_30, pr_relapse_30_50, pr_relapse_above_50, relapse_cutoff, row_sel, relapse_effect, age_min, age_max))
}

#' @export
simsmok_postcalibration <- function(df) {
    invisible(.Call('_workHORSEmisc_simsmok_postcalibration', PACKAGE = 'workHORSEmisc', df))
}

#' @export
simsmok_cig <- function(df) {
    invisible(.Call('_workHORSEmisc_simsmok_cig', PACKAGE = 'workHORSEmisc', df))
}

#' @export
simsmok_cig_sc <- function(df) {
    invisible(.Call('_workHORSEmisc_simsmok_cig_sc', PACKAGE = 'workHORSEmisc', df))
}

#' @export
simsmok_cessation <- function(smok_status, smok_quit_yrs, smok_dur, sex, qimd, age, new_pid, hc_eff, relapse_rn, pr_relapse_below_30, pr_relapse_30_50, pr_relapse_above_50, relapse_cutoff, relapse_effect, age_min = 0L, age_max = 100L) {
    .Call('_workHORSEmisc_simsmok_cessation', PACKAGE = 'workHORSEmisc', smok_status, smok_quit_yrs, smok_dur, sex, qimd, age, new_pid, hc_eff, relapse_rn, pr_relapse_below_30, pr_relapse_30_50, pr_relapse_above_50, relapse_cutoff, relapse_effect, age_min, age_max)
}

#' @export
simsmok_policy_impact_incr <- function(smok_status, smok_quit_yrs, smok_dur, new_pid, hc_eff) {
    .Call('_workHORSEmisc_simsmok_policy_impact_incr', PACKAGE = 'workHORSEmisc', smok_status, smok_quit_yrs, smok_dur, new_pid, hc_eff)
}

#' @export
simsmok_policy_impact_decr <- function(smok_status, smok_quit_yrs, smok_dur, smok_cig, new_pid, hc_eff) {
    .Call('_workHORSEmisc_simsmok_policy_impact_decr', PACKAGE = 'workHORSEmisc', smok_status, smok_quit_yrs, smok_dur, smok_cig, new_pid, hc_eff)
}

#' @export
wtd_ADstat <- function(a, wa, b, wb) {
    .Call('_workHORSEmisc_wtd_ADstat', PACKAGE = 'workHORSEmisc', a, wa, b, wb)
}

#' @export
wtd_KSstat <- function(a, wa, b, wb) {
    .Call('_workHORSEmisc_wtd_KSstat', PACKAGE = 'workHORSEmisc', a, wa, b, wb)
}

